<?php
/**
 * Nomad Constants class file.
 *
 * @since 1.2.0
 *
 * @package Nomad/Helpers
 */

namespace Nomad\Helpers;

if ( ! defined( 'ABSPATH' ) ) exit; // Prevent direct access.

if ( ! class_exists( __NAMESPACE__ . '\\Nomad_Constants' ) ) {

	/**
	 * Nomad Constants Class.
	 *
	 * @since 1.2.0
	 * @final
	 */
	final class Nomad_Constants {

		/**
		 * CHOICES_AMPM
		 *
		 * @since 1.2.0
		 */
		const CHOICES_AMPM = array(
			'am' => 'AM',
			'pm' => 'PM',
		);

		/**
		 * CHOICES_COUNTRY
		 *
		 * @since 1.2.0
		 */
		const CHOICES_COUNTRY = array(
			'AF' => 'Afghanistan',
			'AL' => 'Albania',
			'DZ' => 'Algeria',
			'AS' => 'American Samoa',
			'AD' => 'Andorra',
			'AO' => 'Angola',
			'AI' => 'Anguilla',
			'AQ' => 'Antarctica',
			'AG' => 'Antigua and Barbuda',
			'AR' => 'Argentina',
			'AM' => 'Armenia',
			'AW' => 'Aruba',
			'AU' => 'Australia',
			'AT' => 'Austria',
			'AZ' => 'Azerbaijan',
			'BS' => 'Bahamas',
			'BH' => 'Bahrain',
			'BD' => 'Bangladesh',
			'BB' => 'Barbados',
			'BY' => 'Belarus',
			'BE' => 'Belgium',
			'BZ' => 'Belize',
			'BJ' => 'Benin',
			'BM' => 'Bermuda',
			'BT' => 'Bhutan',
			'BO' => 'Bolivia',
			'BA' => 'Bosnia and Herzegovina',
			'BW' => 'Botswana',
			'BV' => 'Bouvet Island',
			'BR' => 'Brazil',
			'IO' => 'British Indian Ocean Territory',
			'BN' => 'Brunei Darussalam',
			'BG' => 'Bulgaria',
			'BF' => 'Burkina Faso',
			'BI' => 'Burundi',
			'KH' => 'Cambodia',
			'CM' => 'Cameroon',
			'CA' => 'Canada',
			'CV' => 'Cape Verde',
			'KY' => 'Cayman Islands',
			'CF' => 'Central African Republic',
			'TD' => 'Chad',
			'CL' => 'Chile',
			'CN' => 'China',
			'CX' => 'Christmas Island',
			'CC' => 'Cocos (Keeling) Islands',
			'CO' => 'Colombia',
			'KM' => 'Comoros',
			'CG' => 'Congo',
			'CD' => 'Congo, the Democratic Republic of the',
			'CK' => 'Cook Islands',
			'CR' => 'Costa Rica',
			'CI' => 'Cote D\'Ivoire',
			'HR' => 'Croatia',
			'CU' => 'Cuba',
			'CY' => 'Cyprus',
			'CZ' => 'Czech Republic',
			'DK' => 'Denmark',
			'DJ' => 'Djibouti',
			'DM' => 'Dominica',
			'DO' => 'Dominican Republic',
			'EC' => 'Ecuador',
			'EG' => 'Egypt',
			'SV' => 'El Salvador',
			'GQ' => 'Equatorial Guinea',
			'ER' => 'Eritrea',
			'EE' => 'Estonia',
			'ET' => 'Ethiopia',
			'FK' => 'Falkland Islands (Malvinas)',
			'FO' => 'Faroe Islands',
			'FJ' => 'Fiji',
			'FI' => 'Finland',
			'FR' => 'France',
			'GF' => 'French Guiana',
			'PF' => 'French Polynesia',
			'TF' => 'French Southern Territories',
			'GA' => 'Gabon',
			'GM' => 'Gambia',
			'GE' => 'Georgia',
			'DE' => 'Germany',
			'GH' => 'Ghana',
			'GI' => 'Gibraltar',
			'GR' => 'Greece',
			'GL' => 'Greenland',
			'GD' => 'Grenada',
			'GP' => 'Guadeloupe',
			'GU' => 'Guam',
			'GT' => 'Guatemala',
			'GN' => 'Guinea',
			'GW' => 'Guinea-Bissau',
			'GY' => 'Guyana',
			'HT' => 'Haiti',
			'HM' => 'Heard Island and Mcdonald Islands',
			'VA' => 'Holy See (Vatican City State)',
			'HN' => 'Honduras',
			'HK' => 'Hong Kong',
			'HU' => 'Hungary',
			'IS' => 'Iceland',
			'IN' => 'India',
			'ID' => 'Indonesia',
			'IR' => 'Iran, Islamic Republic of',
			'IQ' => 'Iraq',
			'IE' => 'Ireland',
			'IL' => 'Israel',
			'IT' => 'Italy',
			'JM' => 'Jamaica',
			'JP' => 'Japan',
			'JO' => 'Jordan',
			'KZ' => 'Kazakhstan',
			'KE' => 'Kenya',
			'KI' => 'Kiribati',
			'KP' => 'Korea, Democratic People\'s Republic of',
			'KR' => 'Korea, Republic of',
			'KW' => 'Kuwait',
			'KG' => 'Kyrgyzstan',
			'LA' => 'Lao People\'s Democratic Republic',
			'LV' => 'Latvia',
			'LB' => 'Lebanon',
			'LS' => 'Lesotho',
			'LR' => 'Liberia',
			'LY' => 'Libyan Arab Jamahiriya',
			'LI' => 'Liechtenstein',
			'LT' => 'Lithuania',
			'LU' => 'Luxembourg',
			'MO' => 'Macao',
			'MK' => 'Macedonia, the Former Yugoslav Republic of',
			'MG' => 'Madagascar',
			'MW' => 'Malawi',
			'MY' => 'Malaysia',
			'MV' => 'Maldives',
			'ML' => 'Mali',
			'MT' => 'Malta',
			'MH' => 'Marshall Islands',
			'MQ' => 'Martinique',
			'MR' => 'Mauritania',
			'MU' => 'Mauritius',
			'YT' => 'Mayotte',
			'MX' => 'Mexico',
			'FM' => 'Micronesia, Federated States of',
			'MD' => 'Moldova, Republic of',
			'MC' => 'Monaco',
			'MN' => 'Mongolia',
			'MS' => 'Montserrat',
			'MA' => 'Morocco',
			'MZ' => 'Mozambique',
			'MM' => 'Myanmar',
			'NA' => 'Namibia',
			'NR' => 'Nauru',
			'NP' => 'Nepal',
			'NL' => 'Netherlands',
			'AN' => 'Netherlands Antilles',
			'NC' => 'New Caledonia',
			'NZ' => 'New Zealand',
			'NI' => 'Nicaragua',
			'NE' => 'Niger',
			'NG' => 'Nigeria',
			'NU' => 'Niue',
			'NF' => 'Norfolk Island',
			'MP' => 'Northern Mariana Islands',
			'NO' => 'Norway',
			'OM' => 'Oman',
			'PK' => 'Pakistan',
			'PW' => 'Palau',
			'PS' => 'Palestinian Territory, Occupied',
			'PA' => 'Panama',
			'PG' => 'Papua New Guinea',
			'PY' => 'Paraguay',
			'PE' => 'Peru',
			'PH' => 'Philippines',
			'PN' => 'Pitcairn',
			'PL' => 'Poland',
			'PT' => 'Portugal',
			'PR' => 'Puerto Rico',
			'QA' => 'Qatar',
			'RE' => 'Reunion',
			'RO' => 'Romania',
			'RU' => 'Russian Federation',
			'RW' => 'Rwanda',
			'SH' => 'Saint Helena',
			'KN' => 'Saint Kitts and Nevis',
			'LC' => 'Saint Lucia',
			'PM' => 'Saint Pierre and Miquelon',
			'VC' => 'Saint Vincent and the Grenadines',
			'WS' => 'Samoa',
			'SM' => 'San Marino',
			'ST' => 'Sao Tome and Principe',
			'SA' => 'Saudi Arabia',
			'SN' => 'Senegal',
			'CS' => 'Serbia and Montenegro',
			'SC' => 'Seychelles',
			'SL' => 'Sierra Leone',
			'SG' => 'Singapore',
			'SK' => 'Slovakia',
			'SI' => 'Slovenia',
			'SB' => 'Solomon Islands',
			'SO' => 'Somalia',
			'ZA' => 'South Africa',
			'GS' => 'South Georgia and the South Sandwich Islands',
			'ES' => 'Spain',
			'LK' => 'Sri Lanka',
			'SD' => 'Sudan',
			'SR' => 'Suriname',
			'SJ' => 'Svalbard and Jan Mayen',
			'SZ' => 'Swaziland',
			'SE' => 'Sweden',
			'CH' => 'Switzerland',
			'SY' => 'Syrian Arab Republic',
			'TW' => 'Taiwan, Province of China',
			'TJ' => 'Tajikistan',
			'TZ' => 'Tanzania, United Republic of',
			'TH' => 'Thailand',
			'TL' => 'Timor-Leste',
			'TG' => 'Togo',
			'TK' => 'Tokelau',
			'TO' => 'Tonga',
			'TT' => 'Trinidad and Tobago',
			'TN' => 'Tunisia',
			'TR' => 'Turkey',
			'TM' => 'Turkmenistan',
			'TC' => 'Turks and Caicos Islands',
			'TV' => 'Tuvalu',
			'UG' => 'Uganda',
			'UA' => 'Ukraine',
			'AE' => 'United Arab Emirates',
			'GB' => 'United Kingdom',
			'US' => 'United States',
			'UM' => 'United States Minor Outlying Islands',
			'UY' => 'Uruguay',
			'UZ' => 'Uzbekistan',
			'VU' => 'Vanuatu',
			'VE' => 'Venezuela',
			'VN' => 'Viet Nam',
			'VG' => 'Virgin Islands, British',
			'VI' => 'Virgin Islands, U.S.',
			'WF' => 'Wallis and Futuna',
			'EH' => 'Western Sahara',
			'YE' => 'Yemen',
			'ZM' => 'Zambia',
			'ZW' => 'Zimbabwe',
		);

		/**
		 * CHOICES_COUNTRY_FULL
		 *
		 * @since 1.2.0
		 */
		const CHOICES_COUNTRY_FULL = array(
			'Afghanistan'                                  => 'Afghanistan',
			'Albania'                                      => 'Albania',
			'Algeria'                                      => 'Algeria',
			'American Samoa'                               => 'American Samoa',
			'Andorra'                                      => 'Andorra',
			'Angola'                                       => 'Angola',
			'Anguilla'                                     => 'Anguilla',
			'Antarctica'                                   => 'Antarctica',
			'Antigua and Barbuda'                          => 'Antigua and Barbuda',
			'Argentina'                                    => 'Argentina',
			'Armenia'                                      => 'Armenia',
			'Aruba'                                        => 'Aruba',
			'Australia'                                    => 'Australia',
			'Austria'                                      => 'Austria',
			'Azerbaijan'                                   => 'Azerbaijan',
			'Bahamas'                                      => 'Bahamas',
			'Bahrain'                                      => 'Bahrain',
			'Bangladesh'                                   => 'Bangladesh',
			'Barbados'                                     => 'Barbados',
			'Belarus'                                      => 'Belarus',
			'Belgium'                                      => 'Belgium',
			'Belize'                                       => 'Belize',
			'Benin'                                        => 'Benin',
			'Bermuda'                                      => 'Bermuda',
			'Bhutan'                                       => 'Bhutan',
			'Bolivia'                                      => 'Bolivia',
			'Bosnia and Herzegovina'                       => 'Bosnia and Herzegovina',
			'Botswana'                                     => 'Botswana',
			'Bouvet Island'                                => 'Bouvet Island',
			'Brazil'                                       => 'Brazil',
			'British Indian Ocean Territory'               => 'British Indian Ocean Territory',
			'Brunei Darussalam'                            => 'Brunei Darussalam',
			'Bulgaria'                                     => 'Bulgaria',
			'Burkina Faso'                                 => 'Burkina Faso',
			'Burundi'                                      => 'Burundi',
			'Cambodia'                                     => 'Cambodia',
			'Cameroon'                                     => 'Cameroon',
			'Canada'                                       => 'Canada',
			'Cape Verde'                                   => 'Cape Verde',
			'Cayman Islands'                               => 'Cayman Islands',
			'Central African Republic'                     => 'Central African Republic',
			'Chad'                                         => 'Chad',
			'Chile'                                        => 'Chile',
			'China'                                        => 'China',
			'Christmas Island'                             => 'Christmas Island',
			'Cocos (Keeling) Islands'                      => 'Cocos (Keeling) Islands',
			'Colombia'                                     => 'Colombia',
			'Comoros'                                      => 'Comoros',
			'Congo'                                        => 'Congo',
			'Congo, the Democratic Republic of the'        => 'Congo, the Democratic Republic of the',
			'Cook Islands'                                 => 'Cook Islands',
			'Costa Rica'                                   => 'Costa Rica',
			'Cote D\'Ivoire'                               => 'Cote D\'Ivoire',
			'Croatia'                                      => 'Croatia',
			'Cuba'                                         => 'Cuba',
			'Cyprus'                                       => 'Cyprus',
			'Czech Republic'                               => 'Czech Republic',
			'Denmark'                                      => 'Denmark',
			'Djibouti'                                     => 'Djibouti',
			'Dominica'                                     => 'Dominica',
			'Dominican Republic'                           => 'Dominican Republic',
			'Ecuador'                                      => 'Ecuador',
			'Egypt'                                        => 'Egypt',
			'El Salvador'                                  => 'El Salvador',
			'Equatorial Guinea'                            => 'Equatorial Guinea',
			'Eritrea'                                      => 'Eritrea',
			'Estonia'                                      => 'Estonia',
			'Ethiopia'                                     => 'Ethiopia',
			'Falkland Islands (Malvinas)'                  => 'Falkland Islands (Malvinas)',
			'Faroe Islands'                                => 'Faroe Islands',
			'Fiji'                                         => 'Fiji',
			'Finland'                                      => 'Finland',
			'France'                                       => 'France',
			'French Guiana'                                => 'French Guiana',
			'French Polynesia'                             => 'French Polynesia',
			'French Southern Territories'                  => 'French Southern Territories',
			'Gabon'                                        => 'Gabon',
			'Gambia'                                       => 'Gambia',
			'Georgia'                                      => 'Georgia',
			'Germany'                                      => 'Germany',
			'Ghana'                                        => 'Ghana',
			'Gibraltar'                                    => 'Gibraltar',
			'Greece'                                       => 'Greece',
			'Greenland'                                    => 'Greenland',
			'Grenada'                                      => 'Grenada',
			'Guadeloupe'                                   => 'Guadeloupe',
			'Guam'                                         => 'Guam',
			'Guatemala'                                    => 'Guatemala',
			'Guinea'                                       => 'Guinea',
			'Guinea-Bissau'                                => 'Guinea-Bissau',
			'Guyana'                                       => 'Guyana',
			'Haiti'                                        => 'Haiti',
			'Heard Island and Mcdonald Islands'            => 'Heard Island and Mcdonald Islands',
			'Holy See (Vatican City State)'                => 'Holy See (Vatican City State)',
			'Honduras'                                     => 'Honduras',
			'Hong Kong'                                    => 'Hong Kong',
			'Hungary'                                      => 'Hungary',
			'Iceland'                                      => 'Iceland',
			'India'                                        => 'India',
			'Indonesia'                                    => 'Indonesia',
			'Iran, Islamic Republic of'                    => 'Iran, Islamic Republic of',
			'Iraq'                                         => 'Iraq',
			'Ireland'                                      => 'Ireland',
			'Israel'                                       => 'Israel',
			'Italy'                                        => 'Italy',
			'Jamaica'                                      => 'Jamaica',
			'Japan'                                        => 'Japan',
			'Jordan'                                       => 'Jordan',
			'Kazakhstan'                                   => 'Kazakhstan',
			'Kenya'                                        => 'Kenya',
			'Kiribati'                                     => 'Kiribati',
			'Korea, Democratic People\'s Republic of'      => 'Korea, Democratic People\'s Republic of',
			'Korea, Republic of'                           => 'Korea, Republic of',
			'Kuwait'                                       => 'Kuwait',
			'Kyrgyzstan'                                   => 'Kyrgyzstan',
			'Lao People\'s Democratic Republic'            => 'Lao People\'s Democratic Republic',
			'Latvia'                                       => 'Latvia',
			'Lebanon'                                      => 'Lebanon',
			'Lesotho'                                      => 'Lesotho',
			'Liberia'                                      => 'Liberia',
			'Libyan Arab Jamahiriya'                       => 'Libyan Arab Jamahiriya',
			'Liechtenstein'                                => 'Liechtenstein',
			'Lithuania'                                    => 'Lithuania',
			'Luxembourg'                                   => 'Luxembourg',
			'Macao'                                        => 'Macao',
			'Macedonia, the Former Yugoslav Republic of'   => 'Macedonia, the Former Yugoslav Republic of',
			'Madagascar'                                   => 'Madagascar',
			'Malawi'                                       => 'Malawi',
			'Malaysia'                                     => 'Malaysia',
			'Maldives'                                     => 'Maldives',
			'Mali'                                         => 'Mali',
			'Malta'                                        => 'Malta',
			'Marshall Islands'                             => 'Marshall Islands',
			'Martinique'                                   => 'Martinique',
			'Mauritania'                                   => 'Mauritania',
			'Mauritius'                                    => 'Mauritius',
			'Mayotte'                                      => 'Mayotte',
			'Mexico'                                       => 'Mexico',
			'Micronesia, Federated States of'              => 'Micronesia, Federated States of',
			'Moldova, Republic of'                         => 'Moldova, Republic of',
			'Monaco'                                       => 'Monaco',
			'Mongolia'                                     => 'Mongolia',
			'Montserrat'                                   => 'Montserrat',
			'Morocco'                                      => 'Morocco',
			'Mozambique'                                   => 'Mozambique',
			'Myanmar'                                      => 'Myanmar',
			'Namibia'                                      => 'Namibia',
			'Nauru'                                        => 'Nauru',
			'Nepal'                                        => 'Nepal',
			'Netherlands'                                  => 'Netherlands',
			'Netherlands Antilles'                         => 'Netherlands Antilles',
			'New Caledonia'                                => 'New Caledonia',
			'New Zealand'                                  => 'New Zealand',
			'Nicaragua'                                    => 'Nicaragua',
			'Niger'                                        => 'Niger',
			'Nigeria'                                      => 'Nigeria',
			'Niue'                                         => 'Niue',
			'Norfolk Island'                               => 'Norfolk Island',
			'Northern Mariana Islands'                     => 'Northern Mariana Islands',
			'Norway'                                       => 'Norway',
			'Oman'                                         => 'Oman',
			'Pakistan'                                     => 'Pakistan',
			'Palau'                                        => 'Palau',
			'Palestinian Territory, Occupied'              => 'Palestinian Territory, Occupied',
			'Panama'                                       => 'Panama',
			'Papua New Guinea'                             => 'Papua New Guinea',
			'Paraguay'                                     => 'Paraguay',
			'Peru'                                         => 'Peru',
			'Philippines'                                  => 'Philippines',
			'Pitcairn'                                     => 'Pitcairn',
			'Poland'                                       => 'Poland',
			'Portugal'                                     => 'Portugal',
			'Puerto Rico'                                  => 'Puerto Rico',
			'Qatar'                                        => 'Qatar',
			'Reunion'                                      => 'Reunion',
			'Romania'                                      => 'Romania',
			'Russian Federation'                           => 'Russian Federation',
			'Rwanda'                                       => 'Rwanda',
			'Saint Helena'                                 => 'Saint Helena',
			'Saint Kitts and Nevis'                        => 'Saint Kitts and Nevis',
			'Saint Lucia'                                  => 'Saint Lucia',
			'Saint Pierre and Miquelon'                    => 'Saint Pierre and Miquelon',
			'Saint Vincent and the Grenadines'             => 'Saint Vincent and the Grenadines',
			'Samoa'                                        => 'Samoa',
			'San Marino'                                   => 'San Marino',
			'Sao Tome and Principe'                        => 'Sao Tome and Principe',
			'Saudi Arabia'                                 => 'Saudi Arabia',
			'Senegal'                                      => 'Senegal',
			'Serbia and Montenegro'                        => 'Serbia and Montenegro',
			'Seychelles'                                   => 'Seychelles',
			'Sierra Leone'                                 => 'Sierra Leone',
			'Singapore'                                    => 'Singapore',
			'Slovakia'                                     => 'Slovakia',
			'Slovenia'                                     => 'Slovenia',
			'Solomon Islands'                              => 'Solomon Islands',
			'Somalia'                                      => 'Somalia',
			'South Africa'                                 => 'South Africa',
			'South Georgia and the South Sandwich Islands' => 'South Georgia and the South Sandwich Islands',
			'Spain'                                        => 'Spain',
			'Sri Lanka'                                    => 'Sri Lanka',
			'Sudan'                                        => 'Sudan',
			'Suriname'                                     => 'Suriname',
			'Svalbard and Jan Mayen'                       => 'Svalbard and Jan Mayen',
			'Swaziland'                                    => 'Swaziland',
			'Sweden'                                       => 'Sweden',
			'Switzerland'                                  => 'Switzerland',
			'Syrian Arab Republic'                         => 'Syrian Arab Republic',
			'Taiwan, Province of China'                    => 'Taiwan, Province of China',
			'Tajikistan'                                   => 'Tajikistan',
			'Tanzania, United Republic of'                 => 'Tanzania, United Republic of',
			'Thailand'                                     => 'Thailand',
			'Timor-Leste'                                  => 'Timor-Leste',
			'Togo'                                         => 'Togo',
			'Tokelau'                                      => 'Tokelau',
			'Tonga'                                        => 'Tonga',
			'Trinidad and Tobago'                          => 'Trinidad and Tobago',
			'Tunisia'                                      => 'Tunisia',
			'Turkey'                                       => 'Turkey',
			'Turkmenistan'                                 => 'Turkmenistan',
			'Turks and Caicos Islands'                     => 'Turks and Caicos Islands',
			'Tuvalu'                                       => 'Tuvalu',
			'Uganda'                                       => 'Uganda',
			'Ukraine'                                      => 'Ukraine',
			'United Arab Emirates'                         => 'United Arab Emirates',
			'United Kingdom'                               => 'United Kingdom',
			'United States'                                => 'United States',
			'United States Minor Outlying Islands'         => 'United States Minor Outlying Islands',
			'Uruguay'                                      => 'Uruguay',
			'Uzbekistan'                                   => 'Uzbekistan',
			'Vanuatu'                                      => 'Vanuatu',
			'Venezuela'                                    => 'Venezuela',
			'Viet Nam'                                     => 'Viet Nam',
			'Virgin Islands, British'                      => 'Virgin Islands, British',
			'Virgin Islands, U.S.'                         => 'Virgin Islands, U.S.',
			'Wallis and Futuna'                            => 'Wallis and Futuna',
			'Western Sahara'                               => 'Western Sahara',
			'Yemen'                                        => 'Yemen',
			'Zambia'                                       => 'Zambia',
			'Zimbabwe'                                     => 'Zimbabwe',
		);

		/**
		 * CHOICES_DAY
		 *
		 * @since 1.2.0
		 */
		const CHOICES_DAY = array(
			1  => '01',
			2  => '02',
			3  => '03',
			4  => '04',
			5  => '05',
			6  => '06',
			7  => '07',
			8  => '08',
			9  => '09',
			10 => '10',
			11 => '11',
			12 => '12',
			13 => '13',
			14 => '14',
			15 => '15',
			16 => '16',
			17 => '17',
			18 => '18',
			19 => '19',
			20 => '20',
			21 => '21',
			22 => '22',
			23 => '23',
			24 => '24',
			25 => '25',
			26 => '26',
			27 => '27',
			28 => '28',
			29 => '29',
			30 => '30',
			31 => '31',
		);

		/**
		 * CHOICES_ENABLE_DISABLE
		 *
		 * @since 1.2.0
		 */
		const CHOICES_ENABLE_DISABLE = array(
			'1' => 'Enable',
			'0' => 'Disable',
		);

		/**
		 * CHOICES_ENABLED_DISABLED
		 *
		 * @since 1.2.0
		 */
		const CHOICES_ENABLED_DISABLED = array(
			'1' => 'Enabled',
			'0' => 'Disabled',
		);

		/**
		 * CHOICES_HOUR12
		 *
		 * @since 1.2.0
		 */
		const CHOICES_HOUR12 = array(
			1  => '1',
			2  => '2',
			3  => '3',
			4  => '4',
			5  => '5',
			6  => '6',
			7  => '7',
			8  => '8',
			9  => '9',
			10 => '10',
			11 => '11',
			12 => '12',
		);

		/**
		 * CHOICES_HOUR24
		 *
		 * @since 1.2.0
		 */
		const CHOICES_HOUR24 = array(
			0  => '00',
			1  => '01',
			2  => '02',
			3  => '03',
			4  => '04',
			5  => '05',
			6  => '06',
			7  => '07',
			8  => '08',
			9  => '09',
			10 => '10',
			11 => '11',
			12 => '12',
			13 => '13',
			14 => '14',
			15 => '15',
			16 => '16',
			17 => '17',
			18 => '18',
			19 => '19',
			20 => '20',
			21 => '21',
			22 => '22',
			23 => '23',
		);

		/**
		 * CHOICES_MINUTE
		 *
		 * @since 1.2.0
		 */
		const CHOICES_MINUTE = array(
			0  => '00',
			1  => '01',
			2  => '02',
			3  => '03',
			4  => '04',
			5  => '05',
			6  => '06',
			7  => '07',
			8  => '08',
			9  => '09',
			10 => '10',
			11 => '11',
			12 => '12',
			13 => '13',
			14 => '14',
			15 => '15',
			16 => '16',
			17 => '17',
			18 => '18',
			19 => '19',
			20 => '20',
			21 => '21',
			22 => '22',
			23 => '23',
			24 => '24',
			25 => '25',
			26 => '26',
			27 => '27',
			28 => '28',
			29 => '29',
			30 => '30',
			31 => '31',
			32 => '32',
			33 => '33',
			34 => '34',
			35 => '35',
			36 => '36',
			37 => '37',
			38 => '38',
			39 => '39',
			40 => '40',
			41 => '41',
			42 => '42',
			43 => '43',
			44 => '44',
			45 => '45',
			46 => '46',
			47 => '47',
			48 => '48',
			49 => '49',
			50 => '50',
			51 => '51',
			52 => '52',
			53 => '53',
			54 => '54',
			55 => '55',
			56 => '56',
			57 => '57',
			58 => '58',
			59 => '59',
		);

		/**
		 * CHOICES_MONTH
		 *
		 * @since 1.2.0
		 */
		const CHOICES_MONTH = array(
			1  => 'January',
			2  => 'February',
			3  => 'March',
			4  => 'April',
			5  => 'May',
			6  => 'June',
			7  => 'July',
			8  => 'August',
			9  => 'September',
			10 => 'October',
			11 => 'November',
			12 => 'December',
		);

		/**
		 * CHOICES_MONTH_FULL
		 *
		 * @since 1.2.0
		 */
		const CHOICES_MONTH_FULL = array(
			'January'   => 'January',
			'February'  => 'February',
			'March'     => 'March',
			'April'     => 'April',
			'May'       => 'May',
			'June'      => 'June',
			'July'      => 'July',
			'August'    => 'August',
			'September' => 'September',
			'October'   => 'October',
			'November'  => 'November',
			'December'  => 'December',
		);

		/**
		 * CHOICES_MONTH_SHORT
		 *
		 * @since 1.2.0
		 */
		const CHOICES_MONTH_SHORT = array(
			'Jan' => 'January',
			'Feb' => 'February',
			'Mar' => 'March',
			'Apr' => 'April',
			'May' => 'May',
			'Jun' => 'June',
			'Jul' => 'July',
			'Aug' => 'August',
			'Sep' => 'September',
			'Oct' => 'October',
			'Nov' => 'November',
			'Dec' => 'December',
		);

		/**
		 * CHOICES_ON_OFF
		 *
		 * @since 1.2.0
		 */
		const CHOICES_ON_OFF = array(
			'on'  => 'On',
			'off' => 'Off',
		);

		/**
		 * CHOICES_STATE
		 *
		 * @since 1.2.0
		 */
		const CHOICES_STATE = array(
			'AL' => 'Alabama',
			'AK' => 'Alaska',
			'AZ' => 'Arizona',
			'AR' => 'Arkansas',
			'CA' => 'California',
			'CO' => 'Colorado',
			'CT' => 'Connecticut',
			'DE' => 'Delaware',
			'DC' => 'District of Columbia',
			'FL' => 'Florida',
			'GA' => 'Georgia',
			'HI' => 'Hawaii',
			'ID' => 'Idaho',
			'IL' => 'Illinois',
			'IN' => 'Indiana',
			'IA' => 'Iowa',
			'KS' => 'Kansas',
			'KY' => 'Kentucky',
			'LA' => 'Louisiana',
			'ME' => 'Maine',
			'MD' => 'Maryland',
			'MA' => 'Massachusetts',
			'MI' => 'Michigan',
			'MN' => 'Minnesota',
			'MS' => 'Mississippi',
			'MO' => 'Missouri',
			'MT' => 'Montana',
			'NE' => 'Nebraska',
			'NV' => 'Nevada',
			'NH' => 'New Hampshire',
			'NJ' => 'New Jersey',
			'NM' => 'New Mexico',
			'NY' => 'New York',
			'NC' => 'North Carolina',
			'ND' => 'North Dakota',
			'OH' => 'Ohio',
			'OK' => 'Oklahoma',
			'OR' => 'Oregon',
			'PA' => 'Pennsylvania',
			'RI' => 'Rhode Island',
			'SC' => 'South Carolina',
			'SD' => 'South Dakota',
			'TN' => 'Tennessee',
			'TX' => 'Texas',
			'UT' => 'Utah',
			'VT' => 'Vermont',
			'VA' => 'Virginia',
			'WA' => 'Washington',
			'WV' => 'West Virginia',
			'WI' => 'Wisconsin',
			'WY' => 'Wyoming',
		);

		/**
		 * CHOICES_STATE_FULL
		 *
		 * @since 1.2.0
		 */
		const CHOICES_STATE_FULL = array(
			'Alabama'              => 'Alabama',
			'Alaska'               => 'Alaska',
			'Arizona'              => 'Arizona',
			'Arkansas'             => 'Arkansas',
			'California'           => 'California',
			'Colorado'             => 'Colorado',
			'Connecticut'          => 'Connecticut',
			'Delaware'             => 'Delaware',
			'District of Columbia' => 'District of Columbia',
			'Florida'              => 'Florida',
			'Georgia'              => 'Georgia',
			'Hawaii'               => 'Hawaii',
			'Idaho'                => 'Idaho',
			'Illinois'             => 'Illinois',
			'Indiana'              => 'Indiana',
			'Iowa'                 => 'Iowa',
			'Kansas'               => 'Kansas',
			'Kentucky'             => 'Kentucky',
			'Louisiana'            => 'Louisiana',
			'Maine'                => 'Maine',
			'Maryland'             => 'Maryland',
			'Massachusetts'        => 'Massachusetts',
			'Michigan'             => 'Michigan',
			'Minnesota'            => 'Minnesota',
			'Mississippi'          => 'Mississippi',
			'Missouri'             => 'Missouri',
			'Montana'              => 'Montana',
			'Nebraska'             => 'Nebraska',
			'Nevada'               => 'Nevada',
			'New Hampshire'        => 'New Hampshire',
			'New Jersey'           => 'New Jersey',
			'New Mexico'           => 'New Mexico',
			'New York'             => 'New York',
			'North Carolina'       => 'North Carolina',
			'North Dakota'         => 'North Dakota',
			'Ohio'                 => 'Ohio',
			'Oklahoma'             => 'Oklahoma',
			'Oregon'               => 'Oregon',
			'Pennsylvania'         => 'Pennsylvania',
			'Rhode Island'         => 'Rhode Island',
			'South Carolina'       => 'South Carolina',
			'South Dakota'         => 'South Dakota',
			'Tennessee'            => 'Tennessee',
			'Texas'                => 'Texas',
			'Utah'                 => 'Utah',
			'Vermont'              => 'Vermont',
			'Virginia'             => 'Virginia',
			'Washington'           => 'Washington',
			'West Virginia'        => 'West Virginia',
			'Wisconsin'            => 'Wisconsin',
			'Wyoming'              => 'Wyoming',
		);

		/**
		 * CHOICES_WEEKDAY
		 *
		 * @since 1.2.0
		 */
		const CHOICES_WEEKDAY = array(
			'monday'    => 'Monday',
			'tuesday'   => 'Tuesday',
			'wednesday' => 'Wednesday',
			'thursday'  => 'Thursday',
			'friday'    => 'Friday',
			'saturday'  => 'Saturday',
			'sunday'    => 'Sunday',
		);

		/**
		 * CHOICES_WEEKDAY_FULL
		 *
		 * @since 1.2.0
		 */
		const CHOICES_WEEKDAY_FULL = array(
			'Monday'    => 'Monday',
			'Tuesday'   => 'Tuesday',
			'Wednesday' => 'Wednesday',
			'Thursday'  => 'Thursday',
			'Friday'    => 'Friday',
			'Saturday'  => 'Saturday',
			'Sunday'    => 'Sunday',
		);

		/**
		 * CHOICES_WEEKDAY_SHORT
		 *
		 * @since 1.2.0
		 */
		const CHOICES_WEEKDAY_SHORT = array(
			'Mon' => 'Monday',
			'Tue' => 'Tuesday',
			'Wed' => 'Wednesday',
			'Thu' => 'Thursday',
			'Fri' => 'Friday',
			'Sat' => 'Saturday',
			'Sun' => 'Sunday',
		);

		/**
		 * CHOICES_YES_NO
		 *
		 * @since 1.2.0
		 */
		const CHOICES_YES_NO = array(
			'yes' => 'Yes',
			'no'  => 'No',
		);

	}

}
